NAME=centos65-x86_64
TYPE=RedHat_64
INSTALLER="./isos/CentOS-6.5-x86_64-minimal.iso"
GUESTADDITIONS="./isos/VBoxGuestAdditions_4.3.10.iso"
HDD="${HOME}/VirtualBox VMs/${NAME}/main.vdi"
HDD_SWAP="${HOME}/VirtualBox VMs/${NAME}/swap.vdi"
VBOX_FILE="${HOME}/VirtualBox VMs/${NAME}/${NAME}.vbox"
VBOX_TFTP_DEFAULT="${HOME}/.VirtualBox/TFTP"
VBOX_TFTP="$(pwd)/tftp/"
NATNET=10.0.2.0/24
